### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nanshanvv** [Albresky/HDU-Library-Master#2]
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    run()
  File "main.py", line 33, in run
    preExeTime_details = getNowTime().strptime(
TypeError: strptime() argument 1 must be str, not None
Error: Process completed with exit code 1

Could you tell me how to fix it. Looking forward to your reply!

**Comment by Albresky** [comment]
请检查Secrets中环境变量是否按格式进行设置，然后再尝试触发一次Action。

**Comment by nanshanvv** [comment]
未检测到配置文件，将在config目录下创建配置文件: ./config/config.yaml
登录成功
初始化预约方案...
正在初始化楼层和座位信息...
plan[0]添加成功
预约方案初始化成功
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    run()
  File "main.py", line 33, in run
    preExeTime_details = getNowTime().strptime(
TypeError: strptime() argument 1 must be str, not None
Error: Process completed with exit code 1.

这个是完整的报错信息，我认为Secrets应该没有错误，我再检查一下

**Comment by Albresky** [comment]
> 未检测到配置文件，将在config目录下创建配置文件: ./config/config.yaml 登录成功 初始化预约方案... 正在初始化楼层和座位信息... plan[0]添加成功 预约方案初始化成功 Traceback (most recent call last): File "main.py", line 108, in run() File "main.py", line 33, in run preExeTime_details = getNowTime().strptime( TypeError: strptime() argument 1 must be str, not None Error: Process completed with exit code 1.
> 
> 这个是完整的报错信息，我认为Secrets应该没有错误，我再检查一下

---

已尝试修复，请更新仓库至最新，并反馈运行情况。
谢谢~
