### ISSUE TITLE
运行了没报错但没抢

### ISSUE THREAD

**Issue by Timpaniiiii** [Albresky/HDU-Library-Master#3]
就运行了五分钟 但没有占座

**Comment by Albresky** [comment]
- 请检查环境变量是否设置正确（参考 `readme.md` 中 `二、数据字段格式说明` 和 `三、Secrets 示例`）
- 请检查账号是否被封禁（请用手机登录尝试订座，若订座正常，则未被封禁，否则请找图书馆5F老师解封账号）
- **PS** 
  -  最新版仓库代码不会导致封禁，如果未更新你的仓库，请及时 `Update`

**Comment by Timpaniiiii** [comment]
佬，我是五天前重新 fork的 然后前几天用都还是正常的 然后账号也没封🥹

**Comment by Albresky** [comment]
> 就运行了五分钟 但没有占座

---

你好，请问该问题后来还出现过吗？
如果问题依然存在，麻烦提供一下日志，谢谢~

**Comment by Timpaniiiii** [comment]
请求次数加了一次 延迟时间加了点就好了

**Comment by Albresky** [comment]
> 请求次数加了一次 延迟时间加了点就好了

---

好的，谢谢回复~


`PS`：**建议立即将仓库同步至最新**，以免 `Action` 中 **泄露隐私信息**（你添加 `print(res)` 代码后，Action 日志会打印出你的订座详情，可以尝试手动删除 `Action` 的历史运行记录）

如果想更改请求次数和延迟，请通过设置环境变量 `HLMMAXTRIALS` 和 `HLMDELAY`。

谢谢

**Comment by Timpaniiiii** [comment]
新的是其他不需要修改了嘛

**Comment by Albresky** [comment]
> 新的是其他不需要修改了嘛

---

有其他需要，请直接修改或添加环境变量，无需修改代码。
谢谢~

**Comment by Timpaniiiii** [comment]
> > 新的是其他不需要修改了嘛
> 
> 有其他需要，请直接修改或添加环境变量，无需修改代码。 谢谢~



好的好的
