### ISSUE TITLE
预约失败的问题

### ISSUE THREAD

**Issue by guxina** [Albresky/HDU-Library-Master#5]
![8EB012D3-C0BD-48E4-B633-6F2FA30B400E](https://github.com/Albresky/HDU-Library-Master/assets/100247664/0e9a79a9-be46-4892-97a4-8e86885b4e8d)
好几次出现这样的问题是怎么回事呀

**Comment by Albresky** [comment]
- 更新仓库到最新版本
- 如果之前有手动设置 `HLMMAXTRIALS` 环境变量，请将其 `删除` 或更新为 `不大于2的正整数`

如果遇到其他问题，欢迎提 issue（并附上错误日志），谢谢~

**Comment by gxaaaaa** [comment]
![AC564EB3-497E-47E1-9222-7150946AE2E6](https://github.com/Albresky/HDU-Library-Master/assets/145570372/0ec7eee8-d58a-49bc-8bf1-cb40e0dec1a3)
这几天一直初始化失败

**Comment by Albresky** [comment]
已尝试修复，请更新仓库到最新版本，谢谢

**Comment by Albresky** [comment]
> ![AC564EB3-497E-47E1-9222-7150946AE2E6](https://user-images.githubusercontent.com/145570372/274107011-0ec7eee8-d58a-49bc-8bf1-cb40e0dec1a3.png) 这几天一直初始化失败

---
你好，请 fork [这个仓库](https://github.com/Albresky/HDU-Library-Master)，不要fork其他人的，不然无法同步到最新版本。谢谢。
